source 'https://rubygems.org'

gem 'coffee-script'
gem 'font-awesome-sass'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'jekyll', '~> 1.4.2'
gem 'jekyll-assets', '~> 0.7.4'
gem 'sass'
gem 'uglifier'
