source 'https://rubygems.org'

gem 'coffee-script'
gem 'font-awesome-sass'
gem 'guard'
gem 'guard-livereload', '~> 2.3.0'
gem 'jekyll', '~> 2.0.0'
gem 'jekyll-assets', '~> 0.9.2'
gem 'sass'
gem 'uglifier'
